name: Generate GitHub Profile Stats

on:
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/stats.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate profile summary cards

    steps:
      - name: Check out profile repository
        uses: actions/checkout@v4

      - name: Generate static GitHub statistics
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 1
          EXCLUDE: ""
          AUTO_PUSH: true
